SELECT * FROM gravityvectortoolkit.normalpointg
where ToLocationId = 2328171;CREATE TABLE `normalpointg` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `FromLocationId` int(11) DEFAULT NULL,
  `ToLocationId` int(11) DEFAULT NULL,
  `ClusterIndex` double DEFAULT NULL,
  `GridId` double DEFAULT NULL,
  `Latitude` double DEFAULT NULL,
  `Longitude` double DEFAULT NULL,
  `SpeedOverGround` double DEFAULT NULL,
  `CourseOverGround` double DEFAULT NULL,
  `DistanceMedian` double DEFAULT NULL,
  `MaxDistanceLeft` double DEFAULT NULL,
  `MaxDistanceRight` double DEFAULT NULL,
  `DistanceStdDevLeft` double DEFAULT NULL,
  `DistanceStdDevRight` double DEFAULT NULL,
  `MaxLesserSpeedDiff` double DEFAULT NULL,
  `MaxGreaterSpeedDiff` double DEFAULT NULL,
  `LesserSpeedStdDev` double DEFAULT NULL,
  `GreaterSpeedStdDev` double DEFAULT NULL,
  `MaxLesserCourseDiff` double DEFAULT NULL,
  `MaxGreaterCourseDiff` double DEFAULT NULL,
  `LesserCourseStdDev` double DEFAULT NULL,
  `GreaterCourseStdDev` double DEFAULT NULL,
  `DataCount` double DEFAULT NULL,
  `PositionGeometry` geometry NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE KEY `idx_normalpointg_FromLocationId_ToLocationId_ClusterIndex_GridId` (`FromLocationId`,`ToLocationId`,`ClusterIndex`,`GridId`),
  KEY `idx_Speed_Course_Dist` (`SpeedOverGround`,`CourseOverGround`,`DistanceMedian`,`MaxDistanceLeft`,`MaxDistanceRight`,`DistanceStdDevLeft`,`DistanceStdDevRight`),
  SPATIAL KEY `idx_normalpointg_PositionGeometry` (`PositionGeometry`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
